name: foodyman
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.8.5+5

environment:
  sdk: '>=3.10.0'
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter

  #base:
  dio: any
  intl: any
  get_it: any
  google_fonts: any
  pull_to_refresh: any
  flutter_screenutil: any
  proste_indexed_stack: any


  http: ^1.6.0
  crypto: ^3.0.7
  auto_route: ^11.1.0
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  flutter_riverpod: ^3.1.0
  riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.4
  permission_handler: ^12.0.1
  flutter_displaymode: ^0.7.0
  provider: ^6.1.5+1
  web_socket_channel: ^3.0.3
  
  #ui
  jiffy: ^6.4.4
  lottie: ^3.3.2
  confetti: ^0.8.0
  flutter_svg: ^2.2.3
  share_plus: ^12.0.1
  card_swiper: ^3.0.1
  sms_autofill: ^2.4.1
  url_launcher: ^6.3.2
  flutter_remix: ^0.0.3
  webview_flutter: ^4.13.0
  intl_phone_field: ^3.2.0
  connectivity_plus: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  top_snackbar_flutter: ^3.3.0
  flutter_masked_text2: ^0.9.1
  flutter_html: ^3.0.0
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  visibility_detector: ^0.4.0+2
  flutter_swipe_detector: ^2.0.0
  flutter_advanced_switch: ^3.1.0
  flutter_carousel_slider: ^1.1.0
  floating_draggable_widget: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  app_tracking_transparency: ^2.0.6+1

  #media:
  image: ^4.7.2
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  cached_network_image: ^3.4.1

  #maps:
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_place:
    git:
      url: https://github.com/Muhammadyunusxon/google_place.git
  osm_nominatim: ^4.0.1
  google_maps_flutter: ^2.14.0

  #auth:
  google_sign_in: ^6.2.3
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  app_links: ^7.0.0
  dartz: ^0.10.1

  #firebase:
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  payfast:
    git:
      url: https://github.com/Muhammadyunusxon/payfast_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_logo.png'
  adaptive_icon_foreground: 'assets/images/app_logo.png'
  adaptive_icon_background: "#ffffff"