name: Semantic PR
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic:
    uses: RokctAI/shared-workflows/.github/workflows/universal-semantic.yml@main
    permissions:
      pull-requests: read
      statuses: write
    secrets: inherit
